### PR TITLE
Standard errors on heritability estimates

### PR DESCRIPTION
**Pull request by caleblareau**
Hi @kbroman, I've found the package to be incredibly useful (as well as your blog post from a couple of years ago). One thing that I was lacking for computing my heritability estimates were the standard errors on those estimates. 

I've implemented a straightforward use of the Hessian to get the variance on the MLE estimate while the default function execution stays the same. There may be a more elegant way of doing this, but I couldn't get any Hessian estimates from the `optimise()` function. Further, one may want to enable this with the Cpp optimization, but I kept it simple and require the R optimization. 

-Caleb

### CODE REVIEW

**Comment by kbroman** [comment]
Cool; could you try adding a test in [`tests/testthat/`](https://github.com/kbroman/lmmlite/tree/master/tests/testthat)?

**Comment by caleblareau** [comment]
Verified anecdotally (one phenotype) but it was a pretty strong test... [see here](https://github.com/caleblareau/lmmlite/blob/master/tests/testthat/test-h2-se.R)

**Comment by kbroman** [comment]
What do you think about including `hsq_se` as a component of the output list, rather than as an attribute to the `hsq` component?

**Comment by caleblareau** [comment]
As a user, adding it to the list would actually be preferred, I think. My implementation was purely out of convenience for the existing code. 

This would also absolve an annoying hiccup I wound up with is the added `as.numeric()` in the final object construction:

https://github.com/kbroman/lmmlite/blob/12b45b2ceb3c67fe1e2ac69f57ed6d9119214b3c/R/lmm.R#L293

**Comment by kbroman** [comment]
Okay cool; I went ahead with that. 

Funny that `hsq*sigmasq` preserves the attributes.

**Pull request merged**
